#!/system/bin/sh

#
# Advanced Synapse loader script
#

source=/system/res/synapse
target=/res/synapse

# Start with remounting rootfs to create the target directory
mount -o remount,rw /
mkdir -p ${target}

# Secure rootfs again
mount -o remount,ro /

# Make /system read-write able (required for some configs)
mount -o remount,rw /system

# Mount tmpfs at target directory
mount -v -w -o size=4M,mode=0755 -t tmpfs tmpfs ${target}

# Copy files and prebuild UCI config
/system/bin/synapse-update --no-confirm
