#!/system/bin/sh

#
# Advanced Synapse running config updater script
#

source=/system/res/synapse
target=/res/synapse

#
# Force-stop Synapse application
#
if [ "$1" != "--no-force-stop" ]; then
	echo -n "[*] Force-stopping Synapse application..."

	am force-stop com.af.synapse
	rc=$?

	if [ $rc != 0 ]; then
		echo " Failed..."
		exit 1
	fi

	echo " Done!"
fi

#
# Clean up running config
#
echo -n "[*] Cleaning up running configuration..."

rm -rf ${target}/* > /dev/.synapse-update.log 2>&1
rc=$?

if [ $rc != 0 ]; then
	echo " Failed..."
	exit 1
fi

echo " Done!"

#
# Copy data from source
#
echo -n "[*] Copying data from source..."

cp -rpf ${source}/* ${target} >> /dev/.synapse-update.log 2>&1
rc=$?

if [ $rc != 0 ]; then
	echo " Failed..."
	exit 1
fi

echo " Done!"

#
# Setting correct file permissions on target
#

echo -n "[*] Updating file permissions..."

chmod -R 0755 ${target} >> /dev/.synapse-update.log 2>&1
rc=$?

if [ $rc != 0 ]; then
	echo " Failed..."
	exit 1
fi

echo " Done!"

#
# Rebuild configuration
#
echo -n "[*] Rebuilding UCI configuration..."

/system/bin/uci >> /dev/.synapse-update.log 2>&1
rc=$?

if [ $rc != 0 ]; then
	echo "Failed..."
	exit 1
fi

echo " Done!"
