#!/system/bin/sh

#
# Advanced Synapse running config updater script
#

source=/system/res/synapse
target=/res/synapse

if [ "$1" != "--no-confirm" ]; then
	echo ""
	echo "MAKE SURE SYNAPSE IS CLOSED BEFORE YOU CONTINUE!!! - PRESS ENTER TO CONTINUE!!!"
	read
fi

#
# Clean up running config
#
echo -n "[*] Cleaning up running configuration..."

rm -rf ${target}/* > /dev/.synapse-update.log 2>&1
rc=$?

if [ $rc != 0 ]; then
	echo " Failed..."
	exit 1
fi

echo " Done!"

#
# Copy data from source
#
echo -n "[*] Copying data from source..."

cp -rpf ${source}/* ${target} >> /dev/.synapse-update.log 2>&1
rc=$?

if [ $rc != 0 ]; then
	echo " Failed..."
	exit 1
fi

echo " Done!"

#
# Setting correct file permissions on target
#

echo -n "[*] Updating file permissions..."

chmod -R 0755 ${target} >> /dev/.synapse-update.log 2>&1
rc=$?

if [ $rc != 0 ]; then
	echo " Failed..."
	exit 1
fi

echo " Done!"

#
# Rebuild configuration
#
echo -n "[*] Rebuilding UCI configuration..."

/system/bin/uci >> /dev/.synapse-update.log 2>&1
rc=$?

if [ $rc != 0 ]; then
	echo "Failed..."
	exit 1
fi

echo " Done!"
